### ISSUE TITLE
Update BETTER example files

### ISSUE THREAD

**Issue by aviveiros11** [BuildingSync/use-cases#5]
input better example files have changed

**Comment by nllong** [comment]
Can we just grab some BSync files from the JCC data that we've anonymized? Like this one?

[205.xml.zip](https://github.com/BuildingSync/use-cases/files/7204424/205.xml.zip)

**Comment by nllong** [comment]
Let me know when you are done tweaking and I can re-upload the data and run BETTER to make sure the results work.
